### ISSUE TITLE
BusinessId wordt niet geupdate bij het maken van een nieuw bedrijf

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#1]

**Comment by larsluijendijk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BusinessId wordt niet geupdate bij het maken van een nieuw bedrijf](https://trello.com/c/JYqpIHYG/12-businessid-wordt-niet-geupdate-bij-het-maken-van-een-nieuw-bedrijf)

**Comment by larsluijendijk** [comment]
fixed.

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(V-0.1) BusinessId wordt niet geupdate bij het maken van een nieuw bedrijf](https://trello.com/c/cN0TVmYD/159-v-01-businessid-wordt-niet-geupdate-bij-het-maken-van-een-nieuw-bedrijf)
