### ISSUE TITLE
De edit van vacatures moet verwijdert worden

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#10]

**Comment by Tippe** [comment]
moet wel

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [De edit van vacatures moet verwijdert worden](https://trello.com/c/i9R6U3U8/158-de-edit-van-vacatures-moet-verwijdert-worden)
