### ISSUE TITLE
Het maken van een factuurnummer gaat fout

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#12]
De code haalt het ID op van een vorig factuur en doet dan +1. Maar het haalt helaas alleen de eerste op waardoor alle factuurnummers (2) woden.

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Het maken van een factuurnummer gaat fout](https://trello.com/c/Bq52cEd7/60-het-maken-van-een-factuurnummer-gaat-fout)

**Comment by larsluijendijk** [comment]
fixed: het factuurnummer wordt nu hetzelfde als het id van de vacature die gemaakt is.
