### ISSUE TITLE
Email sturen als je je wachtwoord vergeten bent werkt niet

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#13]
De code stuurt geen mail. Komt steeds error

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Email sturen als je je wachtwoord vergeten bent werkt niet](https://trello.com/c/4wkdizQU/65-email-sturen-als-je-je-wachtwoord-vergeten-bent-werkt-niet)

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Email sturen als je je wachtwoord vergeten bent werkt niet](https://trello.com/c/4wkdizQU/65-email-sturen-als-je-je-wachtwoord-vergeten-bent-werkt-niet)

**Comment by larsluijendijk** [comment]
fixed: er is nu een connectie met de mail server. De mail kan niet worden verzonden lokaal.

**Comment by larsluijendijk** [comment]
fixed: er is nu een connectie met de mail server. De mail kan niet worden verzonden lokaal.
