### ISSUE TITLE
De footer in de homepagina is zichtbaar

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#14]

**Comment by Tippe** [comment]
Fixed, code gecomment

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [De footer in de homepagina is zichtbaar](https://trello.com/c/1V3cL5ow/66-de-footer-in-de-homepagina-is-zichtbaar)
