### ISSUE TITLE
Bij het registreren moet je een logo selecteren, anders lukt de registratie niet

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#15]

**Comment by Tippe** [comment]
Fixed, ervoor gezorgd dat logo ook leeg mag blijven in de auth controller

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bij het registreren moet je een logo selecteren, anders lukt de registratie niet](https://trello.com/c/DF5Q1Mpx/67-bij-het-registreren-moet-je-een-logo-selecteren-anders-lukt-de-registratie-niet)
