### ISSUE TITLE
Logo uploaden knop bij de registratie pagina werkt niet correct

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#16]
De knop werkt wel. Dan kan je een afbeelding uploaden. Maar als je op de tekst klikt dat in de button staat 'Afbeelding'. Dan werkt het niet.

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Logo uploaden knop bij de registratie pagina werkt niet correct](https://trello.com/c/JyHL5w0l/70-logo-uploaden-knop-bij-de-registratie-pagina-werkt-niet-correct)

**Comment by larsluijendijk** [comment]
fixed: er was een div die er voor zorgde dat het niet werkte
