### ISSUE TITLE
Als je aan het registreren bent en je klikt op enter worden de velden gesubmit terwijl je nog niet klaar bent met alles invullen

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#18]

**Comment by larsluijendijk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als je aan het registreren bent en je klikt op enter worden de velden gesubmit terwijl je nog niet klaar bent met alles invullen](https://trello.com/c/vykJ8Ebd/87-als-je-aan-het-registreren-bent-en-je-klikt-op-enter-worden-de-velden-gesubmit-terwijl-je-nog-niet-klaar-bent-met-alles-invullen)

**Comment by Tippe** [comment]
Gefixed jquery functie zorgt ervoor dat je niet op enter kunt klikken
