### ISSUE TITLE
Bij het wachtwoord veranderen hoef je maar 1 keer je nieuwe wachtwoord in te vullen. Dit moet 2 keer gebeuren.

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#24]

**Comment by larsluijendijk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bij het wachtwoord veranderen hoef je maar 1 keer je nieuwe wachtwoord in te vullen. Dit moet 2 keer gebeuren.](https://trello.com/c/dGb9ULoT/94-bij-het-wachtwoord-veranderen-hoef-je-maar-1-keer-je-nieuwe-wachtwoord-in-te-vullen-dit-moet-2-keer-gebeuren)

**Comment by Tippe** [comment]
fixed
