### ISSUE TITLE
Datum notatie moet nederlands DD-MM-YYYY bij de start en eind datum vacatures

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#25]

**Comment by larsluijendijk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Datum notatie moet nederlands DD-MM-YYYY bij de start en eind datum vacatures](https://trello.com/c/wA5rBvhe/92-datum-notatie-moet-nederlands-dd-mm-yyyy-bij-de-start-en-eind-datum-vacatures)

**Comment by Tippe** [comment]
Fixed gebruik gemaakt van strtotime functie in php
