### ISSUE TITLE
Er voor zorgen dat wanneer er een mail word gestuurd de mail in je postvak komt ipv bij de ongewenste mails

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#27]

**Comment by larsluijendijk** [comment]
fixed: het email is niet meer "gevaarlijk", en de email wordt niet meer naar de spam folder gezet.

**Comment by dogelismo** [comment]
het probleem is nog niet verholpen

**Comment by Tippe** [comment]
Niet meer genoteerd als bug maar als nieuwe feature
