### ISSUE TITLE
(V-0.3.5) PDF van een Factuur laat niet goede lettertype in moet Roboto worden ipv Times New Roman

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#32]

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDF van een Factuur laat niet goede lettertype in moet Roboto worden ipv Times New Roman](https://trello.com/c/je7yDl3a/115-pdf-van-een-factuur-laat-niet-goede-lettertype-in-moet-roboto-worden-ipv-times-new-roman)

**Comment by dogelismo** [comment]
fixed: ik heb google fonts toegevoegd met font-family Roboto en het werkt
