### ISSUE TITLE
(V-0.4)Als je een vacature aanmaakt en bij het betalen doe je niks dan word status 1 en betalingsstatus is leeg

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#33]

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als je een vacature aanmaakt en bij het betalen doe je niks dan word status 1 en betalingsstatus is leeg](https://trello.com/c/ymThY5YM/117-als-je-een-vacature-aanmaakt-en-bij-het-betalen-doe-je-niks-dan-word-status-1-en-betalingsstatus-is-leeg)

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als je een vacature aanmaakt en bij het betalen doe je niks dan word status 1 en betalingsstatus is leeg](https://trello.com/c/ymThY5YM/117-als-je-een-vacature-aanmaakt-en-bij-het-betalen-doe-je-niks-dan-word-status-1-en-betalingsstatus-is-leeg)

**Comment by dogelismo** [comment]
Gefixed: status wordt nu 0, en betaal status op verlopen.
