### ISSUE TITLE
Error message wanneer er geen geldig file type gegeven is bij het uploaden van een afbeelding

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#35]

**Comment by Tippe** [comment]
Fixed, het updaten van een afbeelding stond buiten een if statement waar die in moest

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Het systeem geeft geen foutmelding als er geen geldig bestand wordt gebruikt als logo](https://trello.com/c/3fTpPorR/141-het-systeem-geeft-geen-foutmelding-als-er-geen-geldig-bestand-wordt-gebruikt-als-logo)

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error message wanneer er geen geldig file type gegeven is bij het uploaden van een afbeelding](https://trello.com/c/PKLbjlLP/142-error-message-wanneer-er-geen-geldig-file-type-gegeven-is-bij-het-uploaden-van-een-afbeelding)

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error message wanneer er geen geldig file type gegeven is bij het uploaden van een afbeelding](https://trello.com/c/PKLbjlLP/142-error-message-wanneer-er-geen-geldig-file-type-gegeven-is-bij-het-uploaden-van-een-afbeelding)

**Comment by dogelismo** [comment]
fixed: er is nu een check die de extensie pakt, en die valideert of het een jpg/jpeg/png bestand is. Als dat niet zo is wordt er niks geupload en krijg je het bericht: "Geen geldige extensie.".
