### ISSUE TITLE
(V-0.4)Je kan alle PDF's bekijken zonder dat het van je eigen bedrijf is.

### ISSUE THREAD

**Issue by dogelismo** [larsluijendijk/Altena-Vacature-Bug-Tracking#37]
Je kan de link aanpassen van een pdf, dan wordt een pdf getoond dat niet van je eigen bedrijf is.

**Comment by dogelismo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Je kan alle PDF's bekijken zonder dat het van je eigen bedrijf is.](https://trello.com/c/SXyJAtAe/143-je-kan-alle-pdfs-bekijken-zonder-dat-het-van-je-eigen-bedrijf-is)

**Comment by Tippe** [comment]
Fixed je kan nu alleen die van je eigen bedrijf checken en anders krijg je een error message

**Comment by dogelismo** [comment]
thx

2018-05-18 10:13 GMT+02:00 Tippe <notifications@github.com>:
