### ISSUE TITLE
Op de homepagina sorteert het op ID en niet op start datum.

### ISSUE THREAD

**Issue by dogelismo** [larsluijendijk/Altena-Vacature-Bug-Tracking#38]
Homepagina laat niet de allernieuwste advertentie zien

**Comment by dogelismo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Op de homepagina sorteert het op ID en niet op start datum.](https://trello.com/c/i4aU0Jwh/144-op-de-homepagina-sorteert-het-op-id-en-niet-op-start-datum)

**Comment by Tippe** [comment]
fixed, sorteerd nu op start datum dus de 1e advertentie die je zal zien is heeft de jongste start datum
