### ISSUE TITLE
Na het maken van een account (en bedrijf) kan je de woonplaats aanpassen en zelf iets neerzetten (wat niet de bedoeling is)

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#4]

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Na het maken van een account (en bedrijf) kan je de woonplaats aanpassen en zelf iets neerzetten (wat niet de bedoeling is)](https://trello.com/c/tfsrn8Mk/32-na-het-maken-van-een-account-en-bedrijf-kan-je-de-woonplaats-aanpassen-en-zelf-iets-neerzetten-wat-niet-de-bedoeling-is)

**Comment by larsluijendijk** [comment]
stop


2018-04-06 10:02 GMT+02:00 Tippe <notifications@github.com>:
