### ISSUE TITLE
Wanneer je in superadmin een bedrijfsgegevens aanpast (zoals bedrijfsnaam) dan word dat niet opgeslagen bij alle vacatures, facturen en gebruikers

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#47]

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wanneer je in superadmin een bedrijfsgegevens aanpast (zoals bedrijfsnaam) dan word dat niet opgeslagen bij alle vacatures, facturen en gebruikers](https://trello.com/c/iM3zLSxe/186-wanneer-je-in-superadmin-een-bedrijfsgegevens-aanpast-zoals-bedrijfsnaam-dan-word-dat-niet-opgeslagen-bij-alle-vacatures-facture)

**Comment by dogelismo** [comment]
dit heeft tippe gefixed
