### ISSUE TITLE
Kan woonplaats niet updaten bij bedrijfsgegevens

### ISSUE THREAD

**Issue by Tippe** [larsluijendijk/Altena-Vacature-Bug-Tracking#5]
Alles update zoals het hoort behalve woonplaats

**Comment by larsluijendijk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kan woonplaats niet updaten bij bedrijfsgegevens](https://trello.com/c/VFhLLoIX/33-kan-woonplaats-niet-updaten-bij-bedrijfsgegevens)

**Comment by larsluijendijk** [comment]
Aangepast: het is nu een input i.p.v. een dropdown. Bug is niet meer van toepassing.
