### ISSUE TITLE
Bij het aanpassen van een andere gebruiker in hetzelfde bedrijf krijg je een melding dat het e-mail al bestaat in de database maar dat is de dezelfde e-mail als de gebruiker.

### ISSUE THREAD

**Issue by dogelismo** [larsluijendijk/Altena-Vacature-Bug-Tracking#50]

**Comment by dogelismo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bij het aanpassen van een andere gebruiker in hetzelfde bedrijf krijg je een melding dat het e-mail al bestaat in de database maar dat is de dezelfde e-mail als de gebruiker.](https://trello.com/c/WyLGb9o7/209-bij-het-aanpassen-van-een-andere-gebruiker-in-hetzelfde-bedrijf-krijg-je-een-melding-dat-het-e-mail-al-bestaat-in-de-database-ma)

**Comment by Tippe** [comment]
Fixed, hij haald ook de email van de gebruiker die je aan het  aanpassen op en check of die hetzelfde is dat voert de validatie "is_unique" niet uit
