### ISSUE TITLE
Woonplaats dropdown in de register: Na het kiezen van een woonplaats, blijft de lijst er staan.

### ISSUE THREAD

**Issue by larsluijendijk** [larsluijendijk/Altena-Vacature-Bug-Tracking#9]

**Comment by larsluijendijk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Woonplaats dropdown in de register: Na het kiezen van een woonplaats, blijft de lijst er staan.](https://trello.com/c/ML6JHY0Z/43-woonplaats-dropdown-in-de-register-na-het-kiezen-van-een-woonplaats-blijft-de-lijst-er-staan)

**Comment by larsluijendijk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Woonplaats dropdown in de register: Na het kiezen van een woonplaats, blijft de lijst er staan.](https://trello.com/c/ML6JHY0Z/43-woonplaats-dropdown-in-de-register-na-het-kiezen-van-een-woonplaats-blijft-de-lijst-er-staan)

**Comment by larsluijendijk** [comment]
Aangepast: Woonplaats is geen dropdown meer, bug is niet meer van toepassing.

**Comment by Tippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Woonplaats dropdown in de register: Na het kiezen van een woonplaats, blijft de lijst er staan.](https://trello.com/c/ML6JHY0Z/43-woonplaats-dropdown-in-de-register-na-het-kiezen-van-een-woonplaats-blijft-de-lijst-er-staan)
